from __future__ import annotations

from typing import Protocol

from src.models.order import AccountInfo, OrderRequest, OrderResult, Position


class BrokerProtocol(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def unlock(self) -> None: ...
    def place_order(self, request: OrderRequest) -> OrderResult: ...
    def cancel_order(self, order_id: str) -> bool: ...
    def get_positions(self, market: str | None = None) -> list[Position]: ...
    def get_account_info(self) -> AccountInfo: ...
    def get_orders(self, **kwargs) -> list: ...
    def get_deals(self, **kwargs) -> list: ...
